template-file-path: secure-cicd-ecr-lab/infrastructure/pipeline.yml
parameters:
  LabName: secure-cicd-ecr-lab
  ExistingGitHubOidcProviderArn: arn:aws:iam::288761743924:oidc-provider/token.actions.githubusercontent.com
  GitHubBranch: main
  GitHubRepo: Eric-Obeng/CLOUD_ENG_LABS
tags: {}
